### ISSUE TITLE
h5py-parallel anaconda mpi error

### ISSUE THREAD

**Issue by lukasostrowski** [mikaem/docker-fenics-recipes#3]
I hope this is the correct place to ask such a question, my appologies if not.

When I install h5py-parallel on anaconda (miniconda3) with

`conda install -c spectraldns h5py-parallel python=3`

and afterwards try to import h5py i get the following error:

```
>>> import h5py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "path/to/miniconda3/envs/testh5py/lib/python3.6/site-packages/h5py/__init__.py", line 24, in <module>
    from . import _errors
  File "MPI.pxd", line 62, in init h5py._errors
ValueError: mpi4py.MPI.Message has the wrong size, try recompiling. Expected 40, got 32
```

I used a clean conda env for the installation, so there should not be any conflicts with other packages.

Do I need to specify additional parameters for the installation?

Maybe this information is useful: 
```
>>> mpi4py.MPI.get_vendor()
('MPICH2', (1, 4, 1))
```

**Comment by mikaem** [comment]
Hi
I think you need the conda-forge channel as well for mpi4py. So try `conda install -c conda-forge -c spectraldns h5py-parallel python=3`

**Comment by lukasostrowski** [comment]
Thank you for your fast reply. This solved my problem!
